on:
  workflow_dispatch:
jobs:
  build:
    permissions:
        contents: read
        pages: write
        id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          lfs: true

      - run: |
          nix develop --command make blueprint

      - name: Fix permissions
        run: |
          chmod -c -R +rX "blueprint/web/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: blueprint/web/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4